DIR = Display
BUILD = pxp_v4l2_test.out
LDFLAGS = -lpthread -lstdc++
# Just use the pxp library to get contiguous physical memory for USERPTR testing
# However, be aware that this is not the only way.
CFLAGS = -DGET_CONTI_PHY_MEM_VIA_PXP_LIB
COPY = pxp_v4l2_out_test.sh README_pxp_v4l2

