LOCAL_PATH := $(call my-dir)
ifeq ($(HAVE_FSL_IMX_IPU),true)
include $(CLEAR_VARS)
LOCAL_SRC_FILES := mxc_v4l2_capture.c
LOCAL_CFLAGS += -DBUILD_FOR_ANDROID
LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_SHARED_LIBRARIES := libutils libc
LOCAL_MODULE := mxc-v4l2-capture
LOCAL_MODULE_TAGS := tests
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := mxc_v4l2_overlay.c
LOCAL_CFLAGS += -DBUILD_FOR_ANDROID
LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_SHARED_LIBRARIES := libutils libc
LOCAL_MODULE := mxc-v4l2-overlay
LOCAL_MODULE_TAGS := tests
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := mxc_v4l2_output.c
LOCAL_CFLAGS += -DBUILD_FOR_ANDROID
LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_SHARED_LIBRARIES := libutils libc
LOCAL_MODULE := mxc-v4l2-output
LOCAL_MODULE_TAGS := tests
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := mxc_v4l2_tvin.c
LOCAL_CFLAGS += -DBUILD_FOR_ANDROID
LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_SHARED_LIBRARIES := libutils libc
LOCAL_MODULE := mxc-v4l2-tvin
LOCAL_MODULE_TAGS := tests
include $(BUILD_EXECUTABLE)

endif

include $(CLEAR_VARS)
LOCAL_SRC_FILES := mx8_v4l2_cap_drm.c
LOCAL_C_INCLUDES += $(LOCAL_PATH) $(LIBDRM_IMX)/libdrm-imx/ $(LIBDRM_IMX)/libdrm-imx/include/drm/
LOCAL_MULTILIB := both
LOCAL_CFLAGS += -DBUILD_FOR_ANDROID
LOCAL_SHARED_LIBRARIES := libutils libc
LOCAL_STATIC_LIBRARIES := libdrm
LOCAL_MODULE := mx8_v4l2_cap_drm
LOCAL_MODULE_STEM_32 := mx8_v4l2_cap_drm_32
LOCAL_MODULE_STEM_64 := mx8_v4l2_cap_drm_64
LOCAL_MODULE_TAGS := tests
LOCAL_VENDOR_MODULE := true
include $(BUILD_EXECUTABLE)
