DIR = Display
BUILD = patgen.exe
patgen.exe = patgen.o bitmap.o
LDFLAGS = -lm -lfreetype
CFLAGS = -Os -I. -I$(PKG_CONFIG_SYSROOT_DIR)/usr/include/freetype2 -I$(PKG_CONFIG_SYSROOT_DIR)/usr/include/libpng16
COPY = README_patgen body-font.ttf header-font.ttf K1FS.ttf  LICENSE.K1FS.ttf patgen.tar.gz

