# list of platforms which did not want this test case

CFLAGS += -lpthread

OBJS = $(OBJDIR)/mxc_i2c_slave_test.out

all : $(OBJS)

.PHONY: clean
clean :
	rm -f $(OBJS)

#
# include the Rules
#
include ../make.rules


