DIR = Display
BUILD = mxc_ipudev_test.out
mxc_ipudev_test.out = mxc_ipudev_test.o utils.o
LDFLAGS = -lm -lrt
COPY = ipudev_config_file autorun-ipu.sh \
	stefan_interlaced_320x240_5frames.yv12 wall-1024x768-565.rgb \
	README_ipu
