DIR = Display
BUILD = mxc_fb_test.out mxc_epdc_fb_test.out mxc_epdc_v2_fb_test.out \
       mxc_spdc_fb_test.out mxc_fb_vsync_test.out
LDFLAGS = -lm
COPY = autorun-fb.sh mxc_tve_test.sh desk240x180-565.rgb daisy-640x480-565.rgb \
       rose-800x600-565.rgb wall-1024x768-565.rgb pansy-1280x720-565.rgb \
       plumbago-1280x1024-565.rgb testcard-1920x1080-bgra.rgb \
       testcard-1920x1080-565.rgb README
